code/tutorial_app/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('player/', views.player_view, name='player'),
    path('jury/', views.jury_view, name='jury'),
    path('coach/', views.coach_view, name='coach'),
    path('dbmanager/', views.dbmanager_view, name='dbmanager'),
    path('add_player/', views.add_player_view, name='add_player'),
    path('add_jury/', views.add_jury_view, name='add_jury'),
    path('add_coach/', views.add_coach_view, name='add_coach'),
    path('update_stadium/', views.update_stadium_view, name='update_stadium'),
    path('delete_session/', views.delete_session_view, name='delete_session'),
    path('list_stadium/', views.list_stadium_view, name='list_stadium'),
    path('average_rating/', views.average_rating_view, name='average_rating'),
    path('list_player/', views.list_player_view, name='list_player'),
    path('average_height/', views.average_height_view, name='average_height'),
    path('add_new_session/', views.add_new_session_view, name='add_new_session'),
    path('rate_session/', views.rate_session_view, name='rate_session'),
    path('squad/', views.squad_view, name='squad'),
]

code/tutorial_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('tutorial_app.urls')),
    path('admin/', admin.site.urls),
]

code/tutorial_app/forms.py
from django import forms

class PlayerForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    name = forms.CharField(max_length=100)
    surname = forms.CharField(max_length=100)
    date_of_birth = forms.CharField(max_length=100)
    height = forms.IntegerField()
    weight = forms.IntegerField()
    player_position_id = forms.IntegerField()
    position_id = forms.IntegerField()
    player_teams_id = forms.IntegerField()
    team_id = forms.IntegerField()

class JuryForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    name = forms.CharField(max_length=100)
    surname = forms.CharField(max_length=100)
    nationality = forms.CharField(max_length=100)

class CoachForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    name = forms.CharField(max_length=100)
    surname = forms.CharField(max_length=100)
    nationality = forms.CharField(max_length=100)

class UpdateStadiumForm(forms.Form):
    stadium_id = forms.IntegerField()
    new_stadium_name = forms.CharField(max_length=100)

class DeleteSessionForm(forms.Form):
    session_id = forms.IntegerField()

class NewSessionForm(forms.Form):
    session_id = forms.IntegerField()
    jury_name = forms.CharField(max_length=100)
    jury_surname = forms.CharField(max_length=100)
    date = forms.CharField(max_length=100)
    rating = forms.FloatField(required=False)
    time_slot = forms.IntegerField()
    stadium_id = forms.IntegerField()

class RateSessionForm(forms.Form):
    rate = forms.FloatField()
    date = forms.CharField(max_length=100)
    session_id = forms.IntegerField()

class SquadForm(forms.Form):
    session_id = forms.IntegerField()
    player1 = forms.CharField(max_length=100)
    player2 = forms.CharField(max_length=100)
    player3 = forms.CharField(max_length=100)
    player4 = forms.CharField(max_length=100)
    player5 = forms.CharField(max_length=100)
    player6 = forms.CharField(max_length=100)
    position1 = forms.IntegerField()
    position2 = forms.IntegerField()
    position3 = forms.IntegerField()
    position4 = forms.IntegerField()
    position5 = forms.IntegerField()
    position6 = forms.IntegerField()

code/tutorial_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
import mysql.connector
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.db import connection
from django.db import IntegrityError 
from django.db import transaction
from django.shortcuts import render
from .forms import PlayerForm, JuryForm, CoachForm, UpdateStadiumForm, DeleteSessionForm, NewSessionForm, RateSessionForm, SquadForm
import json

def index(request):
    return HttpResponse("view.index function is called")

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        request.session['username'] = username  
        password = request.POST.get('password')

        with connection.cursor() as cursor:
            cursor.execute("SELECT username FROM DatabaseManagers WHERE DatabaseManagers.username = %s AND DatabaseManagers.password = %s", [username, password])
            dbmanager_exists = cursor.fetchone()

        # Check if the username exists in the Players table
        with connection.cursor() as cursor:
            cursor.execute("SELECT Users.username FROM Users INNER JOIN Players ON Users.username = Players.username WHERE Users.username= %s and Users.password= %s;", [username, password])
            player_exists = cursor.fetchone()

        # Check if the username exists in the Juries table
        with connection.cursor() as cursor:
            cursor.execute("SELECT Users.username FROM Users INNER JOIN Juries ON Users.username = Juries.username WHERE Users.username= %s and Users.password= %s;", [username, password])
            jury_exists = cursor.fetchone()

        # Check if the username exists in the Coaches table
        with connection.cursor() as cursor:
            cursor.execute("SELECT Users.username FROM Users INNER JOIN Coaches ON Users.username = Coaches.username WHERE Users.username= %s and Users.password= %s;", [username, password])
            coach_exists = cursor.fetchone()

        if player_exists:
            # Player exists, redirect to player page
            return redirect('player')
        elif jury_exists:
            # Jury exists, redirect to jury page
            return redirect('jury')
        elif coach_exists:
            # Coach exists, redirect to coach page
            return redirect('coach')
        elif dbmanager_exists:
            # Coach exists, redirect to coach page
            return redirect('dbmanager')
        else:
            # Username does not exist or incorrect password, render login page with error message
            error_message = "Invalid username or password"
            return render(request, 'login.html', {'error_message': error_message})
    else:
        # Render the login page
        return render(request, 'login.html')

def add_player_view(request):
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            date_of_birth = form.cleaned_data['date_of_birth']
            height = form.cleaned_data['height']
            weight = form.cleaned_data['weight']
            player_position_id = form.cleaned_data['player_position_id']
            position_id = form.cleaned_data['position_id']
            player_teams_id = form.cleaned_data['player_teams_id']
            team_id = form.cleaned_data['team_id']
            with transaction.atomic():
                try:    
                    with connection.cursor() as cursor:
                        cursor.execute("INSERT INTO Users (username, password, name, surname) VALUES (%s, %s, %s, %s)", [username, password, name, surname])
                        cursor.execute("INSERT INTO Players (username, date_of_birth, height, weight) VALUES (%s, %s, %s, %s)", [username, date_of_birth, height, weight])
                        cursor.execute("INSERT INTO Have_Positions (player_position_id,username, position_id) VALUES (%s,%s, %s)", [player_position_id,username, position_id])
                        cursor.execute("INSERT INTO Player_Registered_Team (player_teams_id,username, team_id) VALUES (%s,%s, %s)", [player_teams_id,username, team_id])
                    
                    success_message = "Player is successfully added."
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','success_message': success_message})
                except Exception as e:
                    error_message = "Error: {}".format(str(e))
                    transaction.set_rollback(True)
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','error_message': error_message})
    else:
        form = PlayerForm()
    return render(request, 'add_player.html', {'form': form})
    
def add_jury_view(request):
    if request.method == 'POST':
        form = JuryForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            nationality = form.cleaned_data['nationality']
            with transaction.atomic():
                try:    
                    with connection.cursor() as cursor:
                        cursor.execute("INSERT INTO Users (username, password, name, surname) VALUES (%s, %s, %s, %s)", [username, password, name, surname])
                        cursor.execute("INSERT INTO Juries (username, nationality) VALUES (%s, %s)", [username, nationality])
                    success_message = "Jury is successfully added."
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','success_message': success_message})
                except Exception as e:
                    error_message = "Error: {}".format(str(e))
                    transaction.set_rollback(True)
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','error_message': error_message})
    else:
        form = JuryForm()
    return render(request, 'add_jury.html', {'form': form})

def add_coach_view(request):
    if request.method == 'POST':
        form = CoachForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            nationality = form.cleaned_data['nationality']
            with transaction.atomic():
                try:    
                    with connection.cursor() as cursor:
                        cursor.execute("INSERT INTO Users (username, password, name, surname) VALUES (%s, %s, %s, %s)", [username, password, name, surname])
                        cursor.execute("INSERT INTO Coaches (username, nationality) VALUES (%s, %s)", [username, nationality])
                    success_message = "Coach is successfully added."
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','success_message': success_message})
                except Exception as e:
                    error_message = "Error: {}".format(str(e))
                    transaction.set_rollback(True)
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','error_message': error_message})
    else:
        form = CoachForm()
    return render(request, 'add_coach.html', {'form': form})

def update_stadium_view(request):
    if request.method == 'POST':
        form = UpdateStadiumForm(request.POST)
        if form.is_valid():
            stadium_id = form.cleaned_data['stadium_id']
            new_stadium_name = form.cleaned_data['new_stadium_name']
            with transaction.atomic():
                try:    
                    with connection.cursor() as cursor:
                        cursor.execute("UPDATE Stadiums SET stadium_name = %s WHERE stadium_id = %s", [new_stadium_name, stadium_id])
                    success_message = "Stadium name is successfully updated."
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','success_message': success_message})
                except Exception as e:
                    error_message = "Error: {}".format(str(e))
                    transaction.set_rollback(True)
                    return render(request, 'dbmanager.html', {'message': 'hey manager!','error_message': error_message})
    else:
        form = UpdateStadiumForm()
    return render(request, 'update_stadium.html', {'form': form})

def delete_session_view(request):
    if request.method == 'POST':
        form = DeleteSessionForm(request.POST)
        if form.is_valid():
            session_id = form.cleaned_data['session_id']

            # Check if the session exists
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM Match_Event WHERE session_id = %s", [session_id])
                session_exists = cursor.fetchone()

            if session_exists:
                try:
                    with transaction.atomic():
                        with connection.cursor() as cursor:
                            cursor.execute("DELETE FROM Players_PlayIn_Matches WHERE session_id = %s", [session_id])
                            cursor.execute("DELETE FROM Match_PlayedBy_Team WHERE session_id = %s", [session_id])
                            cursor.execute("DELETE FROM Match_Event WHERE session_id = %s", [session_id])                    
                    success_message = "Match Session is successfully deleted."
                    return render(request, 'coach.html', {'success_message': success_message})

code/tutorial_app/templates/add_coach.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Coach</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h2>Add Coach</h2>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Coach</button>
    </form>
    <a href="{% url 'dbmanager' %}"><button>Turn Back to Database Manager Dashboard</button></a>

</body>
</html>

code/tutorial_app/templates/add_jury.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Jury</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h2>Add Jury</h2>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Jury</button>
    </form>
    <a href="{% url 'dbmanager' %}"><button>Turn Back to Database Manager Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/add_new_session.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Session</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>Add New Session</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% if success_message %}
        <p>{{ success_message }}</p>
    {% endif %}
    <a href="{% url 'coach' %}"><button>Turn Back to Coach Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/average_height.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Average Height</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    <table>
        <thead>
            <tr>
                <th>Average Height</th>
            </tr>
        </thead>
        <tbody>
             {% for row in query_result %}
            <tr>
                {% for column in row %}
                <td>{{ column }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'player' %}"><button>Turn Back to Player Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/average_rating.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Average Ratings</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    <table>
        <thead>
            <tr>
                <th>Average Rating</th>
                <th>Match Count</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for row in query_result %}
                {% for column in row %}
                <td>{{ column }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'jury' %}"><button>Turn Back to Jury Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/coach.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coach Dashboard</title>
    <style>
        /* Adjust button position */
        button {
            margin-right: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <a href="{% url 'delete_session' %}"><button>Delete Match Session</button></a>
    <a href="{% url 'list_stadium' %}"><button>List Stadiums</button></a>
    <a href="{% url 'add_new_session' %}"><button>Add New Session</button></a>
    <a href="{% url 'squad' %}"><button>Create Squad</button></a>
    <a href="{% url 'login' %}"><button>Logout</button></a>
    

</body>
</html>

code/tutorial_app/templates/dbmanager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager Dashboard</title>
    <style>
        /* Adjust button position */
        button {
            margin-right: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <a href="{% url 'add_player' %}"><button>Add Player</button></a>
    <a href="{% url 'add_jury' %}"><button>Add Jury</button></a>
    <a href="{% url 'add_coach' %}"><button>Add Coach</button></a>
    <a href="{% url 'update_stadium' %}"><button>Update Stadium Name</button></a>
    <a href="{% url 'login' %}"><button>Logout</button></a>
    <!-- Add player-specific content here -->
</body>
</html>

code/tutorial_app/templates/delete_session.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Match Session </title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h2>Delete Match Session</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete Match Session</button>
    </form>
    <a href="{% url 'coach' %}"><button>Turn Back to Coach Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/jury.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jury Dashboard</title>
    <style>
        /* Adjust button position */
        button {
            margin-right: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{message}}</h1>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <a href="{% url 'average_rating' %}"><button>See Average Rating</button></a>
    <a href="{% url 'rate_session' %}"><button>Rate a Session</button></a>
    <a href="{% url 'login' %}"><button>Logout</button></a>
</body>
</html>

code/tutorial_app/templates/list_player.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Played Players</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Surname</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for row in query_result %}
                {% for column in row %}
                <td>{{ column }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'player' %}"><button>Turn Back to Player Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/list_stadium.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stadiums</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{ message }}</h1>
    <table>
        <thead>
            <tr>
                <th>Stadium Name</th>
                <th>Stadium Country</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for row in query_result %}
                {% for column in row %}
                <td>{{ column }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'coach' %}"><button>Turn Back to Coach Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/player.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Player Dashboard</title>
    <style>
        /* Adjust button position */
        button {
            margin-right: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h1>{{message}}</h1>
    {% if success_message %}
    <p>{{ success_message }}</p>
    {% endif %}
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <!-- Add player-specific content here -->
    <a href="{% url 'list_player' %}"><button>List Players Played at Once </button></a>
    <a href="{% url 'average_height' %}"><button>Height of the Most Played Player </button></a>
    <a href="{% url 'login' %}"><button>Logout</button></a>
</body>
</html>

code/tutorial_app/templates/rate_session.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Rate Session</title>
<style>
  /* Adjust button position */
  button {
      margin-top: 50px; /* Change as needed */
  }
</style>
</head>
<body>

<h1>Rate Session</h1>
<p>Enter today's date in the format dd-mm-yyyy</p>

<form method="post">
  {% csrf_token %}
  <div>
    <label for="id_rate">Rate:</label>
    <input type="float" name="rate" id="id_rate" required>
  </div>
  <div>
    <label for="id_date">Date:</label>
    <input type="text" name="date" id="id_date" placeholder="dd-mm-yyyy" required>
  </div>
  <div>
    <label for="id_session_id">Session ID:</label>
    <input type="number" name="session_id" id="id_session_id" required>
  </div>
  <button type="submit">Rate Session</button>
</form>
    <a href="{% url 'jury' %}"><button>Turn Back to Jury Dashboard</button></a>
</body>
</html>

code/tutorial_app/templates/update_stadium.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Stadium Name</title>
    <style>
        /* Adjust button position */
        button {
            margin-top: 50px; /* Change as needed */
        }
    </style>
</head>
<body>
    <h2>Update Stadium Name</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Stadium Name</button>
    </form>
    <a href="{% url 'dbmanager' %}"><button>Turn Back to Database Manager Dashboard</button></a>
</body>
</html>